server:
  port: 8070
spring:
  application:
    name: seckill-sidecar

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true

sidecar:
  #server.port为sidecar监听的端口|sidecar.hostname和port是程序监听的端口号，
  hostname: 127.0.0.1
  port: 8080
  #sidecar.health-uri是程序的可访问的uri地址，它需要返回以下json  "status": "UP"
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health
